### ISSUE TITLE
Recipe summary not converting Unit of Measure

### ISSUE THREAD

**Issue by jymmyboi** [antonkarliner/timer-coffee#10]
**Describe the bug**
Under recipe summary, the steps do not convert the unit of measure from the math to the converted UoM (e.g. 60g)

**To Reproduce**
1. Select any brew method
2. Select any recipe
3. Press the recipe summary

**Expected behavior**
The math should convert to the end Unit of Measure

**Screenshots**
![image](https://github.com/antonkarliner/timer-coffee/assets/67038994/b2e31974-63f4-4a8c-920a-ead43146de13)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 114.0.5735.110

**Comment by jymmyboi** [comment]
Can this be assigned to me?

**Comment by antonkarliner** [comment]
> If we were to not convert however there is still and issue as final coffee amount is not converted but final water amount is.

Interesting, could you provide an example?

**Comment by jymmyboi** [comment]
![image](https://github.com/antonkarliner/timer-coffee/assets/67038994/20d79ba8-9ce9-4475-9392-1c090736d017)

Step 1 has "Pre-wet with (2 x <final_coffee_amount>)g of water."
Step 5 has "Complete the first main pour till (0.6 x <final_water_amount>)g in the next 30s."

**Comment by antonkarliner** [comment]
> ![image](https://user-images.githubusercontent.com/67038994/245498804-20d79ba8-9ce9-4475-9392-1c090736d017.png)
> 
> Step 1 has "Pre-wet with (2 x <final_coffee_amount>)g of water." Step 5 has "Complete the first main pour till (0.6 x <final_water_amount>)g in the next 30s."

I see. The thing is, 1l of water weighs approximately 1kg, therefore, for the sake of simplicity, we count 1ml as 1g.

**Comment by jymmyboi** [comment]
Oh wait, this is different in step 5 there is no () around the <final_water_amount> so it says pour till 500g. That makes sense. 
I thought it was a missing semicolon in recipe_summary.dart (line 26). 
Can have a deeper look tomorrow (Australian time).
