### ISSUE TITLE
Hario v60 Tetsu Kasuya 4:6 Method does not apply entered amount

### ISSUE THREAD

**Issue by notDavid** [antonkarliner/timer-coffee#24]
Hi there, thanks for the app!
Fyi, i noticed this bug:

**To Reproduce**
1. Go to 'Hario v60 > Tetsu Kasuya 4:6 Method'
2. Enter 140 ml. water
3. Click next, play
4. Observe that it will use 300 ml water instead - the default value

**Additional context**
Happens on iPhone, iPad and web app

**Comment by antonkarliner** [comment]
@notDavid hello! Thanks for the feedback. I couldn't reproduce the bug on iPhone and web version (both desktop and mobile). Could you please specify the version of the app (can be found in Settings) and attach screenshots/screen recordings if possible. 

Additionally, you may try to reinstall the app/clear the cache in browser, sometimes it can help.
