### ISSUE TITLE
Remember last entered water amount

### ISSUE THREAD

**Issue by notDavid** [antonkarliner/timer-coffee#25]
Hi there,

every day i have to type in the same amount of water. It keeps resetting back to the default value (250 ml) every time you re-open the app (regardless whether you set it as favorite or not);

Please consider remembering the last entered water amount.

Thank you!

**Comment by antonkarliner** [comment]
@notDavid implemented by [af5cf9d](https://github.com/antonkarliner/timer-coffee/commit/af5cf9d8834045a5a5dd08639f1453569a07a338), will be available in App Store and Google Play in the following days.
