### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by notDavid** [antonkarliner/timer-coffee#27]
Hi there,

A few suggestions based on my recent usage (feel free to disregard and close);

1. When returning to the app x hours later, do not resume from the last time, in case i had closed the app before finishing the last step.

2. Add a button to finish/stop the recipe early, and return Home (somewhere at the bottom left, like the Pause button)

3. Showing the *total* time left instead of just the current step would be useful too

Thank you!

**Comment by antonkarliner** [comment]
Hey!

1. Couldn't reproduce it. Did you "closed" the app, or just "minimized" it (not sure about correct wording for phone, lol).
2. You already have a "back" button in the top left which returns you to previous screen, press it a couple of times – and viola, you're at Home screen.
3. I think it's very important to show the time for the specific step as it allows users to adapt their water flow speed. However, it might be a good idea to show the total recipe time, but I couldn't figure out how to do it without cluttering the screen and confusing users. If you have any design suggestions – I'm open to discuss :)

**Comment by antonkarliner** [comment]
@notDavid closing the issue due to inactivity, feel free to reopen in case you'll have more ideas.

**Comment by antonkarliner** [comment]
@notDavid  closing the issue due to inactivity, feel free to reopen in case you'll have more ideas.

**Comment by antonkarliner** [comment]
@notDavid Thanks for providing additional context! The thing is that management of app state in background in mobile OSes (especially iOS) is quite tricky. Especially if we account for the fact that some people may want to minimize the app for a second and then come back (to check a notification for example). However, if you have an elegant solution to this – PR's are always welcome :)

A possible solution for your use case could be to just press the back button a couple of times to return to the previous screen, which will be much quicker than waiting for recipe to end and won't require to force kill the app.

<img width="398" alt="Снимок экрана 2024-04-24 в 10 57 20" src="https://github.com/antonkarliner/timer-coffee/assets/19594480/f52f3ea5-77a7-4786-be43-b84452ce08f8">
