### ISSUE TITLE
Can't switch language to Indonesia

### ISSUE THREAD

**Issue by ganjarsetia** [antonkarliner/timer-coffee#28]
As we know, I did Indonesian translation. Then I tried new [vercel production link](https://timer-coffee-5gpcr4wh1-antonkarliner.vercel.app/) on browser, But I didn't see Indonesia language option. See the screenshot below

**To Reproduce**
1. Go open https://timer-coffee-5gpcr4wh1-antonkarliner.vercel.app/
2. Click on setting icon
3. Click on Language
4. See the language options
5. You will see no Indonesia

**Expected behavior**
It show Indonesia language option. When click it, all the app language change to Indonesia.

**Screenshots**
![image](https://github.com/antonkarliner/timer-coffee/assets/3258090/a3b75fed-ecf3-4085-a8c3-5cc7d3057d30)

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: [e.g. iOS 15
 - Browser: safari

**Comment by antonkarliner** [comment]
Hey, there are some errors in the translated files, I'm currently fixing them. Will be ready later today.
