### ISSUE TITLE
Use lokalise.com tool for better translations

### ISSUE THREAD

**Issue by ganjarsetia** [antonkarliner/timer-coffee#30]
**Is your feature request related to a problem? Please describe.**
Yeah, when we translate into a certain language, we need people who can speak the language manually.

**Describe the solution you'd like**
Sign up https://lokalise.com/ its free for Open Source. With that we can make automated localization. Translate smarter with AI magic.

**Describe alternatives you've considered**
None

**Additional context**
You can close this issue anytime.

**Comment by antonkarliner** [comment]
Hey, thanks for the proposal, However I don’t think we need more closed-source tools for the project. And I'm already utilizing AI to help with translations :)
