### ISSUE TITLE
Typo in Hoffmann V60 1-cup recipe

### ISSUE THREAD

**Issue by robertkb** [antonkarliner/timer-coffee#34]
**Describe the bug**

The first step in the recipe is to add the full amount of water. It should be add 50g. 
**To Reproduce**
1. Open 1-cup recipe
2. Start with default amounts

**Expected behavior**
I think the first step should be the last step. 

**Screenshots**
![image](https://github.com/antonkarliner/timer-coffee/assets/9001420/92433339-31f9-41a8-bcbb-e0ff3bd60308)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS
 - Version 17.4.1

**Additional context**
Started when I downloaded 2.0.0.

**Comment by antonkarliner** [comment]
@robertkb hey, thanks for a good catch! This will be fixed in the future update, in the meantime you can reinstall the app, this should also fix the issue.

**Comment by robertkb** [comment]
Thank you for the fast update. It looks good now.
