### ISSUE TITLE
app.timer.coffee is not laoding

### ISSUE THREAD

**Issue by szymonk92** [antonkarliner/timer-coffee#38]
**Describe the bug**
Web app is not loading. Tried on firefox and chrome. 

**To Reproduce**
Just open the web app

**Expected behavior**
Loading fine

**Screenshots**
![grafik](https://github.com/user-attachments/assets/945b4ab5-6045-43d6-81b6-b4de13543faf)

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - Browser Firefox
 - Version 132.0.2 (64-bit)

**Additional context**
-

**Comment by antonkarliner** [comment]
Hello! Thanks for your report. I wasn't able to reproduce the bug on my devices, could you please share more details about your configuration? Also it's worth checking if something is preventing browser from communicating with Vercel servers / running JavaScript (although not likely if it shows the splash screen...)

**Comment by szymonk92** [comment]
From the console:

`Uncaught SyntaxError: unexpected token: numeric literal
[app.timer.coffee:39:34](https://app.timer.coffee/)
Laden fehlgeschlagen für das <script> mit der Quelle "https://cdn.counter.dev/script.js". [app.timer.coffee:114:116](https://app.timer.coffee/)
Injecting <script> tag. Using callback. [flutter_bootstrap.js:1:1846](https://app.timer.coffee/flutter_bootstrap.js)
Das Components-Objekt sollte nicht mehr verwendet werden. Es wird bald entfernt. [app.timer.coffee](https://app.timer.coffee/)
Source map error: Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://app.timer.coffee/flutter_bootstrap.js
Source Map URL: flutter.js.map

Laden fehlgeschlagen für das <script> mit der Quelle "https://onesignal.com/api/v1/sync/e078a3b4-6cfd-43c6-836a-f59fd96ca7cd/web?callback=__jp0". [app.timer.coffee:1:1](https://app.timer.coffee/)
unreachable code after return statement
[main.dart.js:13117:1](https://app.timer.coffee/main.dart.js)
unreachable code after return statement
[main.dart.js:77187:1](https://app.timer.coffee/main.dart.js)
Uncaught : LateInitializationError: Field '_instance' has not been initialized.
    d https://app.timer.coffee/main.dart.js:3456
    bG https://app.timer.coffee/main.dart.js:47368
    bF8 https://app.timer.coffee/main.dart.js:33515
    <anonymous> https://app.timer.coffee/main.dart.js:147405
    c https://app.timer.coffee/main.dart.js:24
    iA https://app.timer.coffee/main.dart.js:10504
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    $1 https://app.timer.coffee/main.dart.js:47598
    y_ https://app.timer.coffee/main.dart.js:48875
    $0 https://app.timer.coffee/main.dart.js:48056
    FW https://app.timer.coffee/main.dart.js:4996
    tV https://app.timer.coffee/main.dart.js:47979
    cs https://app.timer.coffee/main.dart.js:47591
    h https://app.timer.coffee/main.dart.js:4828
    aaf https://app.timer.coffee/main.dart.js:25344
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    $1 https://app.timer.coffee/main.dart.js:47598
    y_ https://app.timer.coffee/main.dart.js:48875
    $0 https://app.timer.coffee/main.dart.js:48056
    FW https://app.timer.coffee/main.dart.js:4996
    tV https://app.timer.coffee/main.dart.js:47979
    cs https://app.timer.coffee/main.dart.js:47591
    h https://app.timer.coffee/main.dart.js:4828
    cO https://app.timer.coffee/main.dart.js:99333
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    $1 https://app.timer.coffee/main.dart.js:47598
    y_ https://app.timer.coffee/main.dart.js:48875
    $0 https://app.timer.coffee/main.dart.js:48056
    FW https://app.timer.coffee/main.dart.js:4996
    tV https://app.timer.coffee/main.dart.js:47979
    $0 https://app.timer.coffee/main.dart.js:48026
    bPt https://app.timer.coffee/main.dart.js:5028
    bQ1 https://app.timer.coffee/main.dart.js:5030
    $1 https://app.timer.coffee/main.dart.js:47546
    bK9 https://app.timer.coffee/main.dart.js:4807
    <anonymous> https://app.timer.coffee/main.dart.js:147340
    c https://app.timer.coffee/main.dart.js:24
    buJ https://app.timer.coffee/main.dart.js:5035
    beI https://app.timer.coffee/main.dart.js:5146
    vL https://app.timer.coffee/main.dart.js:48883
    a2H https://app.timer.coffee/main.dart.js:47986
    mh https://app.timer.coffee/main.dart.js:47984
    cs https://app.timer.coffee/main.dart.js:47588
    h https://app.timer.coffee/main.dart.js:4828
    0 https://app.timer.coffee/main.dart.js:40383
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    $0 https://app.timer.coffee/main.dart.js:40384
    mo https://app.timer.coffee/main.dart.js:40189
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    mo https://app.timer.coffee/main.dart.js:40193
    0 https://app.timer.coffee/main.dart.js:41549
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    $0 https://app.timer.coffee/main.dart.js:41553
    bft https://app.timer.coffee/main.dart.js:1038
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    bS5 https://app.timer.coffee/main.dart.js:1041
    bft https://app.timer.coffee/main.dart.js:1015
    1 https://app.timer.coffee/main.dart.js:53593
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    aj5 https://app.timer.coffee/main.dart.js:53595
    $1 https://app.timer.coffee/main.dart.js:53585
    1 https://app.timer.coffee/main.dart.js:38914
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    aio https://app.timer.coffee/main.dart.js:38919
    $1 https://app.timer.coffee/main.dart.js:38908
    $1 https://app.timer.coffee/main.dart.js:41559
    bMw https://app.timer.coffee/main.dart.js:7814
    s https://app.timer.coffee/main.dart.js:7790
    n https://app.timer.coffee/flutter_bootstrap.js:1
    didCreateEngineInitializer https://app.timer.coffee/flutter_bootstrap.js:1
    beQ https://app.timer.coffee/main.dart.js:8271
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    beQ https://app.timer.coffee/main.dart.js:8273
    bfI https://app.timer.coffee/main.dart.js:37882
    s https://app.timer.coffee/main.dart.js:4838
    $2 https://app.timer.coffee/main.dart.js:47604
    i https://app.timer.coffee/main.dart.js:4824
    bfI https://app.timer.coffee/main.dart.js:37884
    <anonymous> https://app.timer.coffee/main.dart.js:147958
    <anonymous> https://app.timer.coffee/main.dart.js:147954
    dartProgram https://app.timer.coffee/main.dart.js:147956
    <anonymous> https://app.timer.coffee/main.dart.js:147958`

**Comment by szymonk92** [comment]
Onesignal.com blocked by browser extensions. Could that be a problem?

**Comment by antonkarliner** [comment]
I see. Thanks a lot for the additional context, it seems that the problem may be indeed with OneSignal (service I use to deliver notifications) being blocked. I will investigate and look for a fix in the following days.

**Comment by szymonk92** [comment]
Thanks, if the service is not required, would be nice to use the app anyway. I believe many people nowadays will have simillar servies blocked in the browser.

**Comment by antonkarliner** [comment]
@szymonk92 I just uploaded the version where OneSignal for web is disabled, please check

**Comment by szymonk92** [comment]
Looks like, it is still calling OneSignal 
![image](https://github.com/user-attachments/assets/be1d3727-1795-4898-a6b7-1f59426bb90b)

**Comment by antonkarliner** [comment]
@szymonk92 yep, missed that bit, please try again.

**Comment by antonkarliner** [comment]
@szymonk92 closing this for now, feel free to reopen in case of further issues.
