### ISSUE TITLE
Grayed out instruction what would be next

### ISSUE THREAD

**Issue by szymonk92** [antonkarliner/timer-coffee#40]
**Is your feature request related to a problem? Please describe.**
During brewing process, would be nice to see what is the next step. As to stir or pour is quite different thing, and one requires kettle, another one spoon (or somethign else). To prepare myself, I would like to kwon what is next when trying out new recipes.

**Describe the solution you'd like**
I could imagine that as light gray text at the bottom of the screen. Probably configurable in settings to turn it on/off(?)

![Screenshot_20241117_124607](https://github.com/user-attachments/assets/53e2c16c-d3a5-48b1-8759-d8370445db01)

**Additional context**
Also, when you miss something, or already did something, swapping to the right could show you the next step, swaping left, previous. That would require some kind of animation, so user know that he did perform the action by himself.

**Comment by antonkarliner** [comment]
This is actually a great idea and I will add it to the to-do list.

Speaking about the navigation to the previous/next steps, I'm not really sure, as it introduces a lot of complexity, and also it doesn't make a lot of sense from the brewing point of view, as it will mess the timing. I think the better way is to use the pause button and then resume when ready.

**Comment by antonkarliner** [comment]
Implemented in 2ab4701. Thanks again for the great idea
